
name: Summary_test_-_the_muezzin


services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.3
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data_newsgroups:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic_kafka
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s


  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.3
    restart: unless-stopped
    depends_on:
      elasticsearch: { condition: service_healthy }
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic_kafka
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s



volumes:
  elasticsearch_data_newsgroups:



networks:
  elastic_kafka:
    driver: bridge



